<a href="https://colab.research.google.com/github/ishikaagarwal055/Data-Science/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create DataFrame

In [ ]:
#import package pandas
import pandas as pd
#1d -> method series
df = pd.Series([1,2,3,4,5])
print(df)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
import pandas as pd
#1d -> method series

#example1
l = [1,2,3,4,5]
df = pd.Series(data=l)
print(df)

#in string values pandas gives datatype as object
#example2
d = {"name":"ishu","age":"19","rollno":123}
df = pd.Series(data=d,index=["name","age","rollno"])
print(df)

#information about pandas
help(pd.Series)

#for suggestion
pd.Series??

0    1
1    2
2    3
3    4
4    5
dtype: int64
name      ishu
age         19
rollno     123
dtype: object

In [ ]:
import pandas as pd
d = {
    "name":["iqra","kajal","anjali","pihu","ishika"],
    "roll_no":[11,12,13,14,15]
}
df = pd.DataFrame(data=d)
print(df)

     name  roll_no
0    iqra       11
1   kajal       12
2  anjali       13
3    pihu       14
4  ishika       15

Load and save data from csv

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/ishikaagarwal055/Data-Science/main/file2%20-%20Sheet1.csv"
df = pd.read_csv(url)
print(df)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

Day

Save and load data from Excel

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/ishikaagarwal055/Data-Science/main/file2.xlsx"
df = pd.read_excel(url)
print(df)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

Save and load data from json

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/ishikaagarwal055/Data-Science/main/file2.json"
df = pd.read_json(url)
print("This is for head")
print(df.head(3))         #shows 3 rows from starting
#head -> starting 5 rows
#print(df.head())
#head -> 2 rows data
print(df.head(-3))        #remove 3 rows from bottom
print("\n")

#tail used for getting last 5 rows data
print("This is for tail")
print(df.tail(2))     #gives data from last
#for negative
print(df.tail(-2))    #remove starting 2 values

This is for head
       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
      name  roll no  marks
0  dheeraj      123     10
1    kunal     1234     20


This is for tail
      name  roll no  marks
3  praveen    12356     40
4   anjali  1234567     50
       name  roll no  marks
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

Shape

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/ishikaagarwal055/Data-Science/main/file2.json"
df = pd.read_json(url)
print(df.shape)
df.info(verbose=True)       #verbose = show,print

(5, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll no  5 non-null      int64
 2   marks    5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

Info()

In [ ]:
import pandas as pd
import numpy as np
url="https://raw.githubusercontent.com/ishikaagarwal055/Data-Science/main/file2.json"
df = pd.read_json(url)
df["salary"] = [100,200,300,np.nan,500]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll no  5 non-null      int64
 2   marks    5 non-null      int64
 3   salary   4 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 292.0+ bytes

Rename()

In [ ]:
# Rename
import pandas as pd
url="https://raw.githubusercontent.com/ishikaagarwal055/Data-Science/main/file2.json"
df = pd.read_json(url)
df.rename(columns={"name":"student_name"})
print(df)
print("\n")

#for changing in original data
df.rename(columns={"name":"student_name"},inplace=True)
print(df)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50


  student_name  roll no  marks
0      dheeraj      123     10
1        kunal     1234     20
2     abhishek    12345     30
3      praveen    12356     40
4       anjali  1234567     50

Describe()

In [ ]:
#describe
import pandas as pd
url="https://raw.githubusercontent.com/ishikaagarwal055/Data-Science/main/file2.json"
df = pd.read_json(url)
df.describe()

            roll no      marks
count  5.000000e+00   5.000000
mean   2.521250e+05  30.000000
std    5.492329e+05  15.811388
min    1.230000e+02  10.000000
25%    1.234000e+03  20.000000
50%    1.234500e+04  30.000000
75%    1.235600e+04  40.000000
max    1.234567e+06  50.000000

# Exercise

In [ ]:
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2,3,5,4,1,3]
}
df = pd.DataFrame(data)
print(df)
print(df.head(2))
print("\n")
print(df.head(-2))
print("\n")
print(df.tail(2))
print("\n")
print(df.tail(-2))
print("\n")
print(df.shape)
print("\n")
print(df.info())
print("\n")
print(df.describe())
print("\n")
print(df.rename(columns={"Name":"Employee_Name"}))
print("\n")
df.rename(columns={"Name":"Employee_Name"},inplace=True)
print("After renaming:")
print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj         IT   60000           5
3     104  Sara    Finance   55000           4
4     105  John         IT   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3


   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj         IT   60000           5
3     104  Sara    Finance   55000           4


   Emp_ID  Name Department  Salary  Experience
4     105  John         IT   48000           1
5     106  Neha         HR   52000           3


   Emp_ID  Name Department  Salary  Experience
2     103   Raj         IT   60000           5
3     104  Sara    Finance   55000           4
4     105  John         IT   48000           1
5     106  Neha         HR   52000           3


(6, 5)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      6 non-null      int64
 1   Name        6 non-null      object
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes
None


           Emp_ID        Salary  Experience
count    6.000000      6.000000    6.000000
mean   103.500000  51666.666667    3.000000
std      1.870829   5316.640543    1.414214
min    101.000000  45000.000000    1.000000
25%    102.250000  48500.000000    2.250000
50%    103.500000  51000.000000    3.000000
75%    104.750000  54250.000000    3.750000
max    106.000000  60000.000000    5.000000


   Emp_ID Employee_Name Department  Salary  Experience
0     101          Amit         IT   50000           2
1     102          Riya         HR   45000           3
2     103           Raj         IT   60000           5
3     104          Sara    Finance   55000           4
4     105          John         IT   48000           1
5     106          Neha         HR   52000           3


After renaming:
   Emp_ID Employee_Name Department  Salary  Experience
0     101          Amit         IT   50000           2
1     102          Riya         HR   45000           3
2     103           Raj         IT   60000           5
3     104          Sara    Finance   55000           4
4     105          John         IT   48000           1
5     106          Neha         HR   52000           3

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/ishikaagarwal055/Data-Science/main/file2.json"
df = pd.read_json(url)
print(df)
# get singe column data
df["name"]
#add single column
df["salary"] = df["marks"] + 100
df
#add single column
df["salary"] = [100,200,300,400,500]
df
df["marks"] = df["salary"] / 2
df
df["increment"] = df["salary"] + (df["salary"]/10)
df
df["holidays"] = df["salary"]/100
df["decrement"] = [10,20,30,40,50]
df.drop("salary", axis=1)
#df.drop(["salary","name"], axis=1)
df
#for deletion from original
df.drop("salary", axis=1, inplace=True)
df

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

       name  roll no  marks  increment  holidays  decrement
0   dheeraj      123   50.0      110.0       1.0         10
1     kunal     1234  100.0      220.0       2.0         20
2  abhishek    12345  150.0      330.0       3.0         30
3   praveen    12356  200.0      440.0       4.0         40
4    anjali  1234567  250.0      550.0       5.0         50

**Row **                     
 loc -> label based           
 iloc -> index based

In [ ]:
import pandas as pd
d = {
    "name":["vishal","virat","vineet"],
    "salary":[100,200,300]
}
df = pd.DataFrame(data=d)

print(df.loc[2,"name"])
print(df.iloc[2,0])
print()

#get single row data
print(df.iloc[1])
print()

#get single row using loc
print(df.loc[1])
print()

#get multiple rows using iloc
print(df.iloc[0:2])
print()

#get multiple rows using loc
print(df.loc[0:3])
print()

#sub data get using iloc
df1 = df.iloc[0:2,[0]] # rows->0,1 and cols ->0 |name
df1
print()

#sub data get using loc
df2 = df.loc[0:1,["name"]]
df2

vineet
vineet

name      virat
salary      200
Name: 1, dtype: object

name      virat
salary      200
Name: 1, dtype: object

     name  salary
0  vishal     100
1   virat     200

     name  salary
0  vishal     100
1   virat     200
2  vineet     300

     name
0  vishal
1   virat

#example

In [ ]:
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2,3,5,4,1,3]
}
df = pd.DataFrame(data)
print(df)

#get single column
df["Emp_ID"]

#add single column
df["leave"] = [10,20,30,40,50,43]
df

#drop column
df.drop("Salary", axis=1)
df

#for deletion from original data
df.drop("Salary", axis=1, inplace=True)
df

# For operations on Row

print(df.loc[1,"Name"])
print(df.iloc[1,1])
print()

#get single row data
print(df.iloc[1])
print()

#get single row data
print(df.loc[1])
print()

#get multiple rows using iloc
print(df.iloc[0:2])
print()

#get multiple rows using loc
print(df.loc[0:3])
print()

#sub data get using iloc
df1 = df.iloc[0:2,[0]] # rows->0,1 and cols ->0 |name
df1
print()

#sub data get using loc
df2 = df.loc[0:1,["Name"]]
df2

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj         IT   60000           5
3     104  Sara    Finance   55000           4
4     105  John         IT   48000           1
5     106  Neha         HR   52000           3
Riya
Riya

Emp_ID         102
Name          Riya
Department      HR
Experience       3
leave           20
Name: 1, dtype: object

Emp_ID         102
Name          Riya
Department      HR
Experience       3
leave           20
Name: 1, dtype: object

   Emp_ID  Name Department  Experience  leave
0     101  Amit         IT           2     10
1     102  Riya         HR           3     20

   Emp_ID  Name Department  Experience  leave
0     101  Amit         IT           2     10
1     102  Riya         HR           3     20
2     103   Raj         IT           5     30
3     104  Sara    Finance           4     40

   Name
0  Amit
1  Riya

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
# filter 1
# df[df["english"] == 95]

# filter 2
#df[df["maths"] < 60]

#physics values less than and equal to 56
#df[(df["physics"] <= 56)]

#maths and english values greater than 90
#df[(df["maths"] > 90) & (df["english"] > 90)]

#df[(df["maths"] > 90) | (df["english"] > 90)]

#names
df[(df["maths"]>90) & (df["english"]>90) & (df["gender"] == "Female")]
# print(df)

     name  gender  physics  maths  english
10  Gowri  Female      100    100      100

# sorting

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)

# by default ascending
# df.sort_values("english")
# df.sort_values("name")

#for descending
df.sort_values("english", ascending=False, inplace=True)
#df.sort_values("name", ascending=False)
df

#by default ascending
df.sort_values(by=['english','maths'],ascending=[False,True])

# by values
# df['name'] = df['name'].str.lower()
# df.sort_values('name')

df['name'] = df['name'].str.lower()
df.sort_values('name', ascending=False)

       name  gender  physics  maths  english
4      usha  Female       67     45       78
6    sundar    Male       12     67       67
11      ram    Male       78     55       47
1    rajesh    Male       96    100       95
3      raja    Male       30     25       40
5     priya  Female       56     46       78
12  murugan    Male       34     89       78
2   moorthy    Male       89     90       70
7   kavitha  Female       78     71       67
13  jenifer  Female       67     88       90
9      hema  Female       71     90       23
10    gowri  Female      100    100      100
8    dinesh    Male       56     45       67
0      arun    Male       88     87       78

In [ ]:
df
df["total"] = df['english']+ df['maths']+ df['english']
df

# add row
df.loc[14] = ["ishika", "Female", "93", "86", "90", "269"]
df

# delete column
df.drop('total',axis=1)
df

# delete row
df.drop(14,axis=0)
df

# update row
df.loc[14] = ["ishuu", "Female", "90", "89", "87", "266"]
df

#update column
# df['total'] = df['english'] + df['maths']
# df

       name  gender physics maths english total
10    gowri  Female     100   100     100   200
1    rajesh    Male      96   100      95   195
13  jenifer  Female      67    88      90   178
4      usha  Female      67    45      78   123
5     priya  Female      56    46      78   124
0      arun    Male      88    87      78   165
12  murugan    Male      34    89      78   167
2   moorthy    Male      89    90      70   160
7   kavitha  Female      78    71      67   138
6    sundar    Male      12    67      67   134
8    dinesh    Male      56    45      67   112
11      ram    Male      78    55      47   102
3      raja    Male      30    25      40    65
9      hema  Female      71    90      23   113
14    ishuu  Female      90    89      87  8789

In [ ]:
#df.drop([6,7,8,9,10,11,12,13,14], inplace=True)
df
df['doj'] = [ '2025-01-01', '2025-02-02', '2025-03-03', '2025-04-04', "2025-05-05", '2025-06-06' ]
df['doj'].dtype

# change string to date
df['doj'] = pd.to_datetime(df['doj'])
df['doj'].dtype
# date operation
df['doj'].dt.year
df['doj'].dt.month
df['doj'].dt.day
df['doj'].dt.day_name

#20 days
df['doj'] + pd.to_timedelta('20 days')    # method 1
df['doj'] + pd.to_timedelta(20,unit='D')  # method 2

1   2025-01-21
4   2025-02-22
5   2025-03-23
0   2025-04-24
2   2025-05-25
3   2025-06-26
Name: doj, dtype: datetime64[ns]

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df
# df.isnull()
df.loc[4,'marks'] = pd.NA
# df.loc[4,'marks'] = None
df.loc[3,"roll no"] = None
df.isnull()

# column count missing values
# df.isnull().sum()

    name  roll no  marks
0  False    False  False
1  False     True  False
2  False    False   True
3  False     True  False
4  False    False   True

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df.isnull()

#sum
df.isnull().sum()

# drop null values by row
df.dropna()

# drop null values from cols
# df.dropna(axis=1, inplace=True)
# df

# fill by zero
df.fillna(0)

# fill na with 100
df.fillna(100)

# rollno -> 200  marks ->100
# df.fillna({'roll no':200, 'marks':100}, inplace=True)
# df

# or
# df['roll no'] = df['roll no'].fillna(200)
# df['marks'] = df['marks'].fillna(100)
# df
# df.loc['marks'] = 100
# df

#marks -> mean | nan fill with average
df['marks'] = df['marks'].fillna(df['marks'].mean())
df

       name    roll no  marks
0   dheeraj      123.0   10.0
1     kunal        NaN   20.0
2  abhishek    12345.0   30.0
3   praveen    12356.0   40.0
4    anjali  1234567.0   50.0

##  Aggregation and group by

In [ ]:
# aggregation
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
# manually
df['marks'].sum()
df['marks'].mean()
df['marks'].min()
df['marks'].max()

df['marks'].agg(['sum', 'mean', 'min', 'max'])

sum     120.0
mean     30.0
min      10.0
max      50.0
Name: marks, dtype: float64

# **concatenate**

In [ ]:
from os import name
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df1 = pd.read_json(url)
# pd.concat([df,df1])  # row

df1.loc[2,"name"] = "ishika"
pd.concat([df,df1], axis=1)  # column

# change abhishek -> your name
# df.loc[2,'name'] = "ishika"

       name    roll no  marks     name    roll no  marks
0   dheeraj      123.0   10.0  dheeraj      123.0   10.0
1     kunal        NaN   20.0    kunal        NaN   20.0
2  abhishek    12345.0    NaN   ishika    12345.0    NaN
3   praveen    12356.0   40.0  praveen    12356.0   40.0
4    anjali  1234567.0   50.0   anjali  1234567.0   50.0